theme: jekyll-theme-minimal
title: 'Proteomics Analysis with Limma'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - title: Setup
    url: setup
  - title: Analysis in limma
    url: limma_proteomics_tutorial
